### ISSUE TITLE
unpublish old npm module

### ISSUE THREAD

**Issue by eddiemonge** [eeue56/generator-elm#2]
https://www.npmjs.com/package/elm-yeoman-generator should be unpublished. Or both since the new published one says to use something else

**Comment by eeue56** [comment]
I'm considering just pulling this down - at the moment a yo generator just doesn't seem to serve as much purpose as I thought it might initially. Are you actually using this?

**Comment by eddiemonge** [comment]
No. Its just disrupting the Yeoman generator list and command line search

**Comment by eeue56** [comment]
Great, well, I've got rid of them for now as I don't see the need in them any more but may revisit later.
